function ax = plotsac(SeisData, HdrData, ax, varargin)
% ax = PLOTSAC(SeisData, HdrData, ax, varargin)
%
% Plots seismograms from data from the sac file generated by ARRIVAL2SAC
% with tagged phase arrivals.
%
% INPUT:
% SeisData      time series data
% HdrData       SAC header
% ax            axes to plot
% varargin      arguments for plot function
%
% OUTPUT:
% ax            axes handle of the plot
% 
% SEE ALSO:
% ARRIVAL2SAC, READSAC
%
% Last modified by Sirawich Pipatprathanporn, 09/15/2021

% gets the information from SAC header
[dt_ref, dt_B, dt_E, fs, npts, dts, tims] = gethdrinfo(HdrData);

x = SeisData;
if true
    %x = detrend(decimate(detrend(x, 1), 5), 1);
    %fs = fs/5;
    x = bandpass(x, fs, 1, 2, 2, 2, 'butter');
end

% plot sesimogram
ax = signalplot(x, fs, dt_B, ax, 'title', [], 'k', varargin{:});

% plot arrival times
phaseNum = 0;
phaseTime = HdrData.T0;
phaseName = HdrData.KT0;
while phaseTime ~= -12345
    vline(ax, dt_ref + seconds(phaseTime), 'LineStyle', '--', ...
        'LineWidth', 1, 'Color', 'r');
    
    [x_pos, y_pos] = norm2trueposition(ax, 1/100, 9/10);
    text(x_pos + (dt_ref - dt_B) + seconds(phaseTime), y_pos, phaseName);
    phaseNum = phaseNum + 1;
    switch phaseNum
        case 1
            phaseTime = HdrData.T1;
            phaseName = HdrData.KT1;
        case 2
            phaseTime = HdrData.T2;
            phaseName = HdrData.KT2;
        case 3
            phaseTime = HdrData.T3;
            phaseName = HdrData.KT3;
        case 4
            phaseTime = HdrData.T4;
            phaseName = HdrData.KT4;
        case 5
            phaseTime = HdrData.T5;
            phaseName = HdrData.KT5;
        case 6
            phaseTime = HdrData.T6;
            phaseName = HdrData.KT6;
        case 7
            phaseTime = HdrData.T7;
            phaseName = HdrData.KT7;
        case 8
            phaseTime = HdrData.T8;
            phaseName = HdrData.KT8;
        case 9
            phaseTime = HdrData.T9;
            phaseName = HdrData.KT9;
        otherwise
            break
    end
end

% adds title
ax.Title.String = sprintf('Origin: %s, ID: %d, Mw = %5.2f', ...
    string(dt_ref), HdrData.USER7, HdrData.MAG);
end